services:
  postgres:
    image: postgres:17
    container_name: postgres-cookie-auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookie-auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis-cookie-auth
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight
    container_name: redis-insight-cookie-auth
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cookie-auth
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
  pgadmin_data: